version: '3.7'

services:
    trip:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./:/
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
