# Generated by Django 3.0.3 on 2020-09-14 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('buying_price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_weight_bought', models.IntegerField(default=0, help_text='Enter the total weight bought')),
                ('total_buying_price', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('loading_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('departure_date', models.DateField()),
                ('selling_price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_weight_sold', models.IntegerField(default=0, help_text='Enter the total weight sold')),
                ('total_selling_price', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('offloading_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('selling_date', models.DateField()),
                ('transport_cost', models.DecimalField(decimal_places=2, default=80000, max_digits=8)),
                ('clearance_cost', models.DecimalField(decimal_places=2, default=9000, max_digits=8)),
                ('broker_expenses', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Trip_info',
            },
        ),
    ]
