# Generated by Django 3.0.3 on 2020-09-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_weight_bought', models.IntegerField(default=0, help_text='Enter the total weight bought')),
                ('total_buying_price', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('loading_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('departure_date', models.DateField()),
                ('comment', models.TextField(blank=True, default='Enter comment if any')),
            ],
            options={
                'verbose_name_plural': 'Loading Details',
            },
        ),
        migrations.CreateModel(
            name='Offloading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_weight_sold', models.IntegerField(default=0, help_text='Enter the total weight sold')),
                ('total_selling_price', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('offloading_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('selling_date', models.DateField()),
                ('comment', models.TextField(blank=True, default='Enter comment if any')),
                ('loading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Loading')),
            ],
            options={
                'verbose_name_plural': 'Offloading Details',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a unique name for the Trip', max_length=200, unique=True)),
                ('created_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TripInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_cost', models.DecimalField(decimal_places=2, default=80000, max_digits=8)),
                ('clearance_cost', models.DecimalField(decimal_places=2, default=9000, max_digits=8)),
                ('broker_expenses', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('comment', models.TextField(blank=True, default='Enter comment if any')),
                ('loading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loading', to='api.Loading')),
                ('offloading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offloading', to='api.Offloading')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tripInfo', to='api.Trip')),
            ],
            options={
                'verbose_name_plural': 'Trip Details',
            },
        ),
        migrations.AddField(
            model_name='offloading',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Trip'),
        ),
        migrations.AddField(
            model_name='loading',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Trip'),
        ),
    ]
