# Generated by Django 3.0.3 on 2020-09-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharesmodel',
            name='profit_share',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=19),
        ),
        migrations.AlterField(
            model_name='triploading',
            name='total_buying_price',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tripoffloading',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tripoffloading',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tripoffloading',
            name='total_selling_price',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=19),
        ),
    ]
