# Generated by Django 3.0.3 on 2020-10-04 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharesmodel',
            old_name='profit',
            new_name='offloading',
        ),
        migrations.RemoveField(
            model_name='sharesmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='sharesmodel',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
