# Generated by Django 3.0.3 on 2020-10-04 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20201004_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharesmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='sharesmodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
