# Generated by Django 3.0.3 on 2020-10-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201004_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharesmodel',
            name='offloading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit', to='api.TripOffloading'),
        ),
    ]
