# Generated by Django 3.0.3 on 2020-09-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200926_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharesmodel',
            name='profit_share',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=19),
        ),
    ]
