# Generated by Django 3.0.3 on 2020-10-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201004_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharesmodel',
            name='profit_share',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
    ]
