# Generated by Django 3.0.3 on 2020-10-07 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201004_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharesmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='sharesmodel',
            name='name',
            field=models.CharField(default='Jose', max_length=200),
        ),
        migrations.AlterField(
            model_name='sharesmodel',
            name='offloading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profits', to='api.TripOffloading'),
        ),
    ]
