# Generated by Django 3.0.3 on 2020-10-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201007_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharesmodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
