# Generated by Django 3.0.3 on 2020-10-08 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201007_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharesmodel',
            old_name='contribution',
            new_name='percentage',
        ),
    ]
