# Generated by Django 3.0.3 on 2020-10-08 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201008_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharesmodel',
            name='percentage',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sharesmodel',
            name='profit_share',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=2),
        ),
    ]
