# Generated by Django 3.0.3 on 2020-10-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201008_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharesmodel',
            name='profit_share',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
    ]
