# Generated by Django 3.0.8 on 2021-01-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_tripexpense_total_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripexpense',
            name='total_expense',
        ),
        migrations.AddField(
            model_name='triprequest',
            name='profit_margin',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='total_expense',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tripexpense',
            name='broker_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tripexpense',
            name='clearance_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tripexpense',
            name='transport_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='triploading',
            name='buying_price_per_kg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='triploading',
            name='loading_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='triploading',
            name='total_buying_price',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='triploading',
            name='total_weight_bought',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tripoffloading',
            name='offloading_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tripoffloading',
            name='selling_price_per_kg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tripoffloading',
            name='total_selling_price',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tripoffloading',
            name='total_weight_sold',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tripshare',
            name='profit_share',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
