# Generated by Django 3.0.8 on 2021-01-28 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20210101_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripexpense',
            name='process_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_expense_details', to='trip.TripRequest'),
        ),
        migrations.AlterField(
            model_name='triploading',
            name='process_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_loading_details', to='trip.TripRequest'),
        ),
        migrations.AlterField(
            model_name='tripoffloading',
            name='process_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_offloading_details', to='trip.TripRequest'),
        ),
    ]
