

# POST http://127.0.0.1:8000/account/login/ HTTP/1.1
# content-type: application/json

# {
#     "username": "Gathiira",
#     "password": "avatar"
# }



GET /account/users HTTP/1.1
Host: 127.0.0.1:8000
Authorization: Token ef90f590ee6c90db8127e896dcc47e26857a36416bf32bcbfea1ec6aa0771e5f



# GET http://127.0.0.1:8000/api/loading HTTP/1.1
# content-type: application/json

